version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: campusconnect-db
    restart: always
    environment:
      POSTGRES_USER: campus_admin
      POSTGRES_PASSWORD: campus_password
      POSTGRES_DB: campusconnect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: